"use strict";
/**
 *

 The function returns an associative array (Objects - {} in JavaScript) where the keys are generated by the groupingFunction.

 For each key, we keep an array of values from arr for which, the groupingFunction returns the same key.

 All keys returned must be strings.

 For example:

 var students = [{
  "name" : "Daniel Taskoff",
  "course" : "Frontend JavaScript"
}, {
  "name" : "Elena Jeleva",
  "course" : "Programming 101"
}, {
  "name" : "Luboslava Dimitrova",
  "course" : "Frontend JavaScript"
}, {
  "name" : "Anton Antonov",
  "course" : "Core Java"
}, {
  "name" : "Nikola Dichev",
  "course" : "Core Java"
}];


 console.log(groupBy(function(student) {
  return student.course;
}, students));

 Which outputs:



 */



var groupBy = function (groupingFunction, arr) {
    var result = {};
    arr.forEach(function (a) {
        if(typeof(result[groupingFunction(a)]) === 'undefined'){
            result[groupingFunction(a)] = [];
        }
        result[groupingFunction(a)].push(a);
    });

    return result;
};

exports.groupBy = groupBy;
